### PR TITLE
Playbook to enable or disable Agave integration in the DE.

### PR DESCRIPTION
**Pull request by slr71**
Enable Agave:

```
$ ansible-playbook -i /path/to/inventory -K single-role.yaml -e "playbook=playbooks/de-agave.yml agave_enabled=true"
```

Disable Agave:

```
$ ansible-playbook -i /path/to/inventory -K single-role.yaml -e "playbook=playbooks/de-agave.yml agave_enabled=false"
```

### CODE REVIEW

**Review by ianmcorvidae — APPROVED** [review]
Looks good to me! One tiny comment which has nothing to even do with the PR itself: you don't need to use the single-role.yaml playbook any more. We had to use it before because the group_vars we wanted to use were in a subdirectory of the playbook directory (i.e., of the root of the repository), so we needed a trick to have the playbook directory be the root, but have the actual playbook be in a different directory. Now that the group_vars are inside the inventories instead, you can just do `ansible-playbook -i <inv> -K playbooks/de-agave.yml -e "agave_enabled=true"`

**Comment by slr71** [comment]
Thanks for the reviews! I'm really glad that `single-role.yaml` isn't required anymore. Having to enter the path to the playbook inside the extra-vars argument was a little annoying.

**Comment by strootman** [comment]
> Having to enter the path to the playbook inside the extra-vars argument was a little annoying.

This was one of the biggest motivations for the refactor!!

**Comment by slr71** [comment]
Heh, I probably should have realized that, but I must have missed that somehow. 😖

**Comment by psarando** [comment]
Heh, I also didn't think of that until now, and I also do not recall mention of that motivation, but now it seems like an obvious benefit 👍

**Pull request merged**
