### PR TITLE
Removed old `de-rm-jex` role/playbook

### PR DESCRIPTION
**Pull request by strootman**

### CODE REVIEW

**Review by slr71 — APPROVED** [review]
LGTM :shipit:

**Comment by slr71** [comment]
I'd missed this earlier, but it appears that `de-rm-jex.yaml` is still referenced in `deploy-all.yaml`. This should be fixed.

**Review by slr71 — CHANGES_REQUESTED** [review]
This is just the formal request for changes from my previous comment.

**Comment by ianmcorvidae** [comment]
I won't do a formal review; other than the issue @dennisroberts71 found (removing this playbook from deploy-all) everything looks good to me.

**Comment by strootman** [comment]
@dennisroberts71 I've made the requested changes

**Review by slr71 — APPROVED** [review]
Looks good to me!

**Pull request merged**
